### ISSUE TITLE
Getting the error while running the project

### ISSUE THREAD

**Issue by zaidjubapu** [razaghimahdi/Shopping-By-KMP#1]
In android iam getting the error while running the project below is the error

Can not extract resource from com.android.aaptcompiler.ParsedResource@aa7f82a.,Can not extract resource from com.android.aaptcompiler.ParsedResource@e986da6.

Execution failed for task ':androidApp:mergeDebugResources'.
> A failure occurred while executing com.android.build.gradle.internal.res.ResourceCompilerRunnable
   > Resource compilation failed (Failed to compile values resource file /Users/zaid/Downloads/Shopping-By-KMP-master/androidApp/build/intermediates/incremental/debug/mergeDebugResources/merged.dir/values/values.xml. Cause: java.lang.IllegalStateException: Can not extract resource from com.android.aaptcompiler.ParsedResource@aa7f82a.,Can not extract resource from com.android.aaptcompiler.ParsedResource@e986da6.). Check logs for more details.

**Comment by razaghimahdi** [comment]
would u please share me full description?

**Comment by razaghimahdi** [comment]
thank u for opening issue, it has been solved. check out last update.
