### ISSUE TITLE
Update Kotlin and dependencies

### ISSUE THREAD

**Issue by pahill** [razaghimahdi/Shopping-By-KMP#13]
Hi there!

Please, could you update your dependencies and Kotlin version? Your sample is on [our samples page](https://www.jetbrains.com/help/kotlin-multiplatform-dev/multiplatform-samples.html) and we'd love it if you could keep it updated.

Thank you so much,
Pamela
Kotlin Developer Advocate @ JetBrains

**Comment by razaghimahdi** [comment]
Hi Pamela,
I hope u doing well. As u mentioned, Kotlin and dependencies updated to the last version. thank u for ur time and the issue.
