### ISSUE TITLE
while re-building the project getting the error

### ISSUE THREAD

**Issue by zaidjubapu** [razaghimahdi/Shopping-By-KMP#2]
> Task :shared:linkDebugFrameworkIosArm64
w: Cannot infer a bundle ID from packages of source files and exported dependencies, use the bundle name instead: shared. Please specify the bundle ID explicitly using the -Xbinary=bundleId=<id> compiler flag.

> Task :androidApp:packageDebug
> Task :shared:packageDebugAndroidTest
> Task :shared:linkDebugFrameworkIosX64
w: Cannot infer a bundle ID from packages of source files and exported dependencies, use the bundle name instead: shared. Please specify the bundle ID explicitly using the -Xbinary=bundleId=<id> compiler flag.

**Comment by razaghimahdi** [comment]
could u pelase share me more detail?

**Comment by zaidjubapu** [comment]
https://www.icloud.com/iclouddrive/087cj4ckzpyOnut78t76a778w#ice_video_20240317-155112
above is the link and i want to know does your project will take 15 min time to re-build ?

**Comment by razaghimahdi** [comment]
Item Unavailable
The owner stopped sharing, or you don’t have permission to open this item.

**Comment by razaghimahdi** [comment]
yeah it could take 15 min to re-build
