### ISSUE TITLE
Images are not loading

### ISSUE THREAD

**Issue by zaidjubapu** [razaghimahdi/Shopping-By-KMP#3]
<img width="299" alt="Screenshot 2024-03-17 at 1 00 53 AM" src="https://github.com/razaghimahdi/Shopping-By-KMP/assets/64311606/8d85402e-2044-4cee-a405-be77a33259bb">

**Comment by zaidjubapu** [comment]
{"result":{"banners":[{"id":1,"banner":"https:\/\/m.media-amazon.com\/images\/I\/614VOsGXsqL._SX1500_.jpg"},{"id":2,"banner":"https:\/\/m.media-amazon.com\/images\/I\/71kFc7PP3PL._SX3000_.jpg"},{"id":3,"banner":"https:\/\/m.media-amazon.com\/images\/I\/717Qv6Rdi+L._SX3000_.jpg"}],"categories":[{"id":1,"name":"Computer","parent":0,"icon":""},{"id":2,"name":"Electronics","parent":0,"icon":""},{"id":3,"name":"Arts & Crafts","parent":0,"icon":""},{"id":4,"name":"Automotive","parent":0,"icon":""},{"id":5,"name":"Baby","parent":0,"icon":""},{"id":6,"name":"Beauty and personal care","parent":0,"icon":""},{"id":7,"name":"Women's Fashion","parent":0,"icon":""},{"id":8,"name":"Men's Fashion","parent":0,"icon":""},{"id":9,"name":"Health and Household","parent":0,"icon":""},{"id":10,"name":"Home and Kitchen","parent":0,"icon":""},{"id":11,"name":"Industrial and Scientific","parent":0,"icon":""},{"id":12,"name":"Luggage","parent":0,"icon":""},{"id":13,"name":"Movies & Television","parent":0,"icon":""},{"id":14,"name":"Pet supplies","parent":0,"icon":""},{"id":15,"name":"Sports and Outdoors","parent":0,"icon":""},{"id":16,"name":"Tools & Home Improvement","parent":0,"icon":""},{"id":17,"name":"Toys and Games","parent":0,"icon":""}],"newest_product":[{"id":1,"title":"MANGOPOP Women's Mock Turtle Neck Slim Fit Long Half Short Sleeve T Shirt Tight Tops Tee","description":"MANGOPOP Women's Mock Turtle Neck Slim Fit Long Half Short Sleeve T Shirt Tight Tops Tee","price":19,"image":"https:\/\/m.media-amazon.com\/images\/W\/MEDIAX_792452-T1\/images\/I\/712koZKUvHL._AC_SX679_.jpg","likes":6,"isLike":true,"rate":3.5},{"id":2,"title":"Amazfit Band 5 Activity Fitness Tracker","description":"Amazfit Band 5 Activity Fitness Tracker with Alexa Built-in, 15-Day Battery Life, Blood Oxygen, Heart Rate, Sleep & Stress Monitoring, 5 ATM Water Resistant, Fitness Watch for Men Women Kids, Black","price":120,"image":"https:\/\/m.media-amazon.com\/images\/W\/MEDIAX_792452-T1\/images\/I\/51ja6ds+pML._AC_SX679_.jpg","likes":2,"isLike":false,"rate":3.5},{"id":3,"title":"Alpine Corporation Weather-resistant Bluetooth Solar-Powered Outdoor Wireless Rock Speaker \u2013 Set of 2, Brown","description":"Alpine Corporation Weather-resistant Bluetooth Solar-Powered Outdoor Wireless Rock Speaker \u2013 Set of 2, Brown","price":320,"image":"https:\/\/m.media-amazon.com\/images\/W\/MEDIAX_792452-T1\/images\/I\/816gTVTqs5L._AC_SL1500_.jpg","likes":0,"isLike":false,"rate":3.5},{"id":4,"title":"Nike model-934","description":"Nike model-934","price":120,"image":"https:\/\/www.deadstock.de\/wp-content\/uploads\/2023\/01\/Jordan-1-Mid-Barely-Grape-DQ8423-501-dead-stock-titel-bild-.jpeg","likes":1,"isLike":false,"rate":3.5},{"id":5,"title":"Nike model-934","description":"Nike model-934","price":120,"image":"https:\/\/www.deadstock.de\/wp-content\/uploads\/2023\/01\/Jordan-1-Mid-Barely-Grape-DQ8423-501-dead-stock-titel-bild-.jpeg","likes":0,"isLike":false,"rate":3.5},{"id":6,"title":"Nike model-934","description":"Nike model-934","price":120,"image":"https:\/\/www.deadstock.de\/wp-content\/uploads\/2023\/01\/Jordan-1-Mid-Barely-Grape-DQ8423-501-dead-stock-titel-bild-.jpeg","likes":1,"isLike":false,"rate":3.5},{"id":7,"title":"Shirt model-131","description":"Shirt model-131","price":13,"image":"https:\/\/img.ltwebstatic.com\/images3_pi\/2022\/08\/22\/1661139363d0af2b9ebc4be1a701c62b3af5e237ef.webp","likes":1,"isLike":false,"rate":3.5}],"address":null,"flash_sale":{"expired_at":"2024-03-21T19:30:36.760250Z","products":[{"id":1,"title":"MANGOPOP Women's Mock Turtle Neck Slim Fit Long Half Short Sleeve T Shirt Tight Tops Tee","description":"MANGOPOP Women's Mock Turtle Neck Slim Fit Long Half Short Sleeve T Shirt Tight Tops Tee","price":19,"image":"https:\/\/m.media-amazon.com\/images\/W\/MEDIAX_792452-T1\/images\/I\/712koZKUvHL._AC_SX679_.jpg","likes":6,"isLike":true,"rate":3.5},{"id":2,"title":"Amazfit Band 5 Activity Fitness Tracker","description":"Amazfit Band 5 Activity Fitness Tracker with Alexa Built-in, 15-Day Battery Life, Blood Oxyg

**Comment by razaghimahdi** [comment]
the main reason could be ur network connection, since server of the app based on Iran. then make sense
